### PR TITLE
Bud 268 split receipt by item

### PR DESCRIPTION
**Pull request by Torious**
### BUD Link
https://jira.budgetlens.tech/browse/BUD-262

### Summary of the PR
Provided the activities for splitting a receipt by items with a list of users.

### Details
This pr includes the split item page which includes the list of items loaded from the get receipt items api and for each item containing a split button takes the user to a checkbox list of split participants where the user checks the participants of that individual item split and then presses continue. The user then presses continue on the item split page and it will submit the post request and return to the choose participants page.

### UI Photo 
image
image

### Checks

- [x] Tested Changes
- [x] UI is similar to Figma (if applicable)
- [x] Frontend links to Backend (if applicable)
- [x] Tests are created and working (if applicable)

### CODE REVIEW

**Review by mamineahmadi — DISMISSED** [review]
All good now.

**Review by mamineahmadi — APPROVED** [review]
This is good now.

**Review by ThatJustin — APPROVED** [review]
Good job.

I love the design also.

**Review by shahdyousefak — APPROVED** [review]
Looks good to me.

**Pull request merged**
