### PR TITLE
added app logo

### PR DESCRIPTION
**Pull request by mamineahmadi**
### BUD Link
_Link to the bud on Jira_

### Summary of the PR
Added app logo, test it to make sure it's good cause I'm not sure

### Details
_Mention any extra details_

### UI Photo 
_Attach an image of the UI (for UI Tasks only). Leave blank if none._

### Checks

- [x] Tested Changes
- [ ] UI is similar to Figma (if applicable)
- [ ] Frontend links to Backend (if applicable)
- [ ] Tests are created and working (if applicable)

### CODE REVIEW

**Review by IsaacMuriuki — DISMISSED** [review]
beautiful logo

**Review by teoPalomino — APPROVED** [review]
Beautiful logo

**Review by ThatJustin — APPROVED** [review]
Finally a logo worthy of us! Nice job getting it done.

**Review by shahdyousefak — APPROVED** [review]
Finally! Thanks Mo.

**Pull request merged**
